### ISSUE TITLE
RBXSource.Master.Zip Being a severe recording virus

### ISSUE THREAD

**Issue by erixlxme** [MaximumADHD/Rbx2Source#60]
The RBXSource.Master.Zip Is being blocked by all 3 default anti viruses and is claimed as a recording virus I have downloaded this 3 times in different days and times and still same result maybe check on your project and remove  those virus because it can lead to potential hate. thanks -erix

**Comment by CloneTrooper1019** [comment]
There’s no virus, I think antivirus programs got upset at the fact that the program tries to auto-update itself, which is understandable. I’ll probably just get rid of this functionality for future releases.
